### ISSUE TITLE
RandomizedTest  should not extend Assert

### ISSUE THREAD

**Issue by obourgain** [randomizedtesting/randomizedtesting#184]
RandomizedTest is extending org.junit.Assert, I think this is for convenience of having assertThat method automatically available in every test class extending RandomizedTest.
This is annoying when using another assertion framework like assertJ or FestAssert that use the same method name.

I know this would be a breaking change, but it would make randomized testing more user friendly at just the cost for current users relying on this implicit presence of assertThat() to use a static import instead.

**Comment by dweiss** [comment]
You don't have to extend RandomizedTest, this is merely a convenience. You can add a custom runner annotation to your own class and import all methods from RandomizedTest statically.

**Comment by obourgain** [comment]
In fact, I am using a superclass from a framework, so I can not remove the inheritance, but I think I should open an issue on this framework.

**Comment by dweiss** [comment]
Oliver, you don't understand -- you should create your own superclass much alike RandomizedTest, on which you can tweak and tune things to your liking. Everyone will have their own requirements, it's impossible to write a single class to suit everyone's needs.

If you look at RandomizedTest you'll see it's a plain abstract class and most of the methods just delegate to other utility classes that can be imported statically (or redelegated from your class).

https://github.com/carrotsearch/randomizedtesting/blob/master/randomized-runner/src/main/java/com/carrotsearch/randomizedtesting/RandomizedTest.java#L32

Having your own "parent" class will also provide you with the benefit of being able to add all annotations that control thread leaks. Look at this one, for example:

https://github.com/elasticsearch/elasticsearch/blob/master/src/test/java/org/elasticsearch/test/ElasticsearchTestCase.java#L81

**Comment by obourgain** [comment]
I understand perfectly, and I am using Elasticsearch's ElasticsearchIntegrationTest, which extends the ElasticsearchTest you linked. ElasticsearchTest is extending Lucene's AbstractRandomizedTest which is itself extending your own RandomizedTest. 
So I can not write a test extending ElasticsearchIntegrationTest (to benefit from all those wonderful annotations an stuff like that) that will not have those assertThat() method inhereited from Assert.

**Comment by dweiss** [comment]
File an issue to ES team then. This is a convenience class, not an obligation.

**Comment by dweiss** [comment]
After some thinking I'll reconsider this for the major refactoring that's coming. I'll see what can be done; it's a breaking-change so it won't come in a point revision for sure.
