### ISSUE TITLE
Rework support for nightly mode group in randomized context

### ISSUE THREAD

**Issue by dweiss** [randomizedtesting/randomizedtesting#218]
This is better done via generic group evaluators, etc.

**Comment by javanna** [comment]
Hi @dweiss I see that `RandomizedTest#isNightly` was deprecated as part of #190 and will be deleted at some point: what is exactly the replacement using group evaluators?

**Comment by dweiss** [comment]
Indeed, an explicit "nightly" group makes little sense if you can create test groups to your likes and desires. There is an element of difficulty, however: you can now enable/ disable test groups entirely, or use filtering expressions which are complex Boolean expressions allowing you to pick, for example, an intersection of two groups. So isGroupEnabled(group) doesn't make sense anymore.

Ideally, I'd remove this possibility entirely. Why do you need to tell whether a group is enabled or not at all?

**Comment by javanna** [comment]
I was looking into removing our usages of `RandomizedTest#isNightly` and found this one: https://github.com/elastic/elasticsearch/blob/master/test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java#L1066 . We randomly perform some optional heavy operation only when running nightly tests. We may just remove that logic, I was curious if there was a one-to-one replacement, which I understand is not the case.

**Comment by dweiss** [comment]
Well... you could simply check for the Boolean value of "tests.nightly" -- you know your build so you know better which type of test filtering you're using (whether it's a complex condition or a trivial group on/off switch). Would this work?

**Comment by dweiss** [comment]
Upon closer inspection removing this may be actually problematic since we rely on nightly in value-scaling methods. I have reworked the code a bit and documented it differently to reflect the changes in test filtering.
