### ISSUE TITLE
Update guava to 19.0-rc3

### ISSUE THREAD

**Issue by rjernst** [randomizedtesting/randomizedtesting#221]
This bug in guava makes developing custom test listeners exceptionally painful:
google/guava#2093

The issue is any exception is logged with just a generic message that gives no stack trace, or even the exception class. The fix will be in 19.0. This is just a request to update that once it is released.

**Comment by dweiss** [comment]
Noted, will do it. Let me know when Guava is available, please.

**Comment by dweiss** [comment]
Given how infrequent the rcs are I decided to fold in 19.0-rc3 (released December 1st).
