### ISSUE TITLE
Make unexpected JVM output available to listeners

### ISSUE THREAD

**Issue by rjernst** [randomizedtesting/randomizedtesting#222]
Currently, any direct jvm output goes to ant logging. This means with the gradle wrapper for junit4, complicated things must be done to try and extract that from groovy's ant wrapper. It would be great if there could be an event type added so a listener could choose what to do with this. Then the existing logging to INFO level could be moved to TextReport.

**Comment by dweiss** [comment]
TextReport doesn't use ANT's loggers, it uses System.out. The output events are in fact already event-based, look here:

https://github.com/randomizedtesting/randomizedtesting/blob/master/junit4-ant/src/main/java/com/carrotsearch/ant/tasks/junit4/listeners/TextReport.java#L421-L436

and here:

https://github.com/randomizedtesting/randomizedtesting/blob/master/junit4-ant/src/main/java/com/carrotsearch/ant/tasks/junit4/listeners/TextReport.java#L483-L520

the problem with output from forked JVM is multiple expectations and heavy constraints (output needs to be buffered on disk for tests that log megabytes of data, etc.). This really took a long time to get right, I wouldn't want to mess with it. I think you need to fork TextReport and create something that will be Gradle-specific (and use Gradle's infrastructure for piping the outputs appropriately)?

**Comment by rjernst** [comment]
I already have a fork of TextReport. But the jvm output is printed to ants logger at info level in the main JUnit4 class, not in text report.

**Comment by dweiss** [comment]
Oh, ok. I see your point. It's actually more complicated than just logging:

https://github.com/randomizedtesting/randomizedtesting/blob/master/junit4-ant/src/main/java/com/carrotsearch/ant/tasks/junit4/JUnit4.java#L1523-L1529

And moving it to an event would mean we'd need to replicate the logic of handling JvmOutputAction somehow. Feel free to try to work this out and provide a PR, Ryan. I can't look into this in the next few days.
