### ISSUE TITLE
additionalClasspathElements option only adds empty strings to classpath

### ISSUE THREAD

**Issue by Anaros** [randomizedtesting/randomizedtesting#225]
In JUnit4Mojo.java you have:

   // Additional dependencies.
    cp.addComment("Additional classpath elements.");
    if (additionalClasspathElements != null && !additionalClasspathElements.isEmpty()) {
      for (String classpathElement : additionalClasspathElements) {
        if (Strings.isNullOrEmpty(classpathElement)) { <-----------------
          cp.addElement("pathelement").addAttribute("location",
              classpathElement);
}}}}}

Shouldn't the line be:
if (!Strings.isNullOrEmpty(classpathElement)) {
?

This was driving me crazy when trying to use the config option.

**Comment by dweiss** [comment]
It surely looks like a bug!
