### ISSUE TITLE
net.sf.proguard:proguard:jar must specify an absolute path

### ISSUE THREAD

**Issue by henrik242** [randomizedtesting/randomizedtesting#231]
I get a strange error in my Gradle build.  Is this a randomizedtesting problem?

    Processing of /home/travis/.gradle/caches/modules-2/files-2.1/com.carrotsearch.randomizedtesting
      /junit4-ant/2.3.4/f671cb9471d984103ccaaf09fcbc7fc6d8be07a0/junit4-ant-2.3.4.pom failed:

    'build.plugins.plugin[com.pyx4me:proguard-maven-plugin].dependencies.dependency.systemPath' 
      for net.sf.proguard:proguard:jar must specify an absolute path but is 
      ${project.basedir}/lib/proguard.jar in com.carrotsearch.randomizedtesting:junit4-ant:2.3.4

**Comment by dweiss** [comment]
Don't know what gradle is doing, but you shouldn't be resolving plugins of the project if you only need it as a dependency. What you see is a dependency required for the build.
