### ISSUE TITLE
Add BiasedNumbers as an alternative to RandomNumbers

### ISSUE THREAD

**Issue by dweiss** [randomizedtesting/randomizedtesting#238]
When selecting random numbers it often is the case that one wants to select certain boundary conditions more often than the whole range at uniform distribution. Examples include:
- min and max of the range
- 0, -1, 1,
- -0.0, +0.0 (for floating points),
- very small numbers (floating points) or very small deviations from min, max.

Methods in BiasedNumbers would be similar to those in RandomNumbers, but would be targeted at selecting the above special conditions more often than the uniform distribution.

**Comment by dsmiley** [comment]
This would be very cool.  I manually "bias" numbers for spatial -- i.e. biasing towards world bounds.
