### ISSUE TITLE
ASCII generator is a lie

### ISSUE THREAD

**Issue by rjernst** [randomizedtesting/randomizedtesting#248]
The ASCII generator and associated randomAsciiXXX methods don't actually generate ascii, they generate alphabetic characters only.  Perhaps this should generate real ascii (although I guess it should be printable ascii maybe) and have a separate alpha generator?

**Comment by dweiss** [comment]
It isn't a lie. You interpret ASCII as a charset (codepage), whereas my original intention was to have something that generates "safe" characters (in terms of the set count of different symbols and compatibility with filesystems, etc.). If you like in a country with mostly latin letters, with a few exceptions (łóżźć) then "ascii" is strongly synonymous with "plain latin characters", although in this case I think I borrowed the idea/code from Lucene, so somebody else had a similar intuition?...

Anyway, you're right in that the name should reflect better what this method does and I have no problem with renaming it "randomAlphaNum" or something like that. I don't think the utility of generating printable ascii characters has that much value (one can do this fairly trivially on their own, if needed). Most use cases of this method (that I used) were for ensuring filesystem-safe stuff or string with a constrained alphabet.

**Comment by dweiss** [comment]
Deprecated those methods and added more explicit randomAsciiLetters* and randomAsciiAlphanum*. Couldn't come up with anything more specific (randomAlphanum would imply full unicode; Latin1 or Iso8859-1 seem even more cryptic than Ascii to me).

**Comment by rjernst** [comment]
Thanks David!

**Comment by dweiss** [comment]
No problem at all, thanks for reporting this! I'll release a point version early next week (let me know if you need it earlier).
