### ISSUE TITLE
Intermitted java.lang.IllegalStateException: Context disposed errors running with Spring @Rule

### ISSUE THREAD

**Issue by lourish** [randomizedtesting/randomizedtesting#249]
Hi I've seeing errors of the following form:

```
java.lang.IllegalStateException: Context disposed: com.carrotsearch.randomizedtesting.RandomizedContext@905a4da for thread: Thread[TEST-LoginPageTest.loginFormAuthenticates-seed#[6DBBF3D9660B1219],5,TGRP-LoginPageTest]
    at __randomizedtesting.SeedInfo.seed([6DBBF3D9660B1219:6E07D5A618E26AF]:0)
    at com.carrotsearch.randomizedtesting.RandomizedContext.checkDisposed(RandomizedContext.java:328)
    at com.carrotsearch.randomizedtesting.RandomizedContext.getPerThread(RandomizedContext.java:317)
    at com.carrotsearch.randomizedtesting.RandomizedContext.getRandomness(RandomizedContext.java:92)
    at com.carrotsearch.randomizedtesting.RandomizedContext.getRandom(RandomizedContext.java:114)
    at uk.gov.cambsfire.authservice.domain.AuthPrototypes.getRandom(AuthPrototypes.java:24)
```

My tests are all formed similar to the following (using Spring Boot and Fluentlenium):
```
@SpringBootTest( webEnvironment = WebEnvironment.RANDOM_PORT)
@FluentConfiguration(driverLifecycle = DriverLifecycle.CLASS)
@RunWith(RandomizedRunner.class)
@ThreadLeakScope(Scope.NONE) //Otherwise tests always fail due to thread generation from Spring/Fluentlenium
public class MyPageTest extends FluentTest {
    @ClassRule
    public static final SpringClassRule SPRING_CLASS_RULE = new SpringClassRule();
    private AuthPrototypes authPrototypes;

    @Rule
    public final SpringMethodRule springMethodRule = new SpringMethodRule();
    
    @Autowired
    private AuthMacros authMacros;

    @PostConstruct
    protected void setUpRandomness() {
        authPrototypes = new AuthPrototypes(RandomizedContext.current());
    }
```
The class `AuthPrototypes` above calls `RandomizedContext.getContext()` as part of the test, and it is this that fails. It seems to work on the first class, fail on the second test class that uses `RandomizedContext`, succeed on the third.

I can provide further detail if needed, I've tried to follow the code path but  all I can see is that new RandomizedContext instances are created at the start of each test but I can't trace what is setting disposed to true for the 'next' test class.

**Comment by dweiss** [comment]
The context is only valid during the duration of the suite (or even a single test) -- the exception is intentional so that you can't accidentally share it.  The same applies to the Random instance that is part of the context. You should get the context "within" the test (or suite hooks) and then it should be fine for the duration of the given scope. 

Check when is "PostConstruct" called, I'm not sure mixing the test runner and some dependency injection is going to work here. Same thing for this:
{code}
@ThreadLeakScope(Scope.NONE) //Otherwise tests always fail due to thread generation from Spring/Fluentlenium
{code}
if it's some kind of "service" threads that escape your tests, they can be ignored with a filter. In general, no thread should escape a test so by ignoring them you're risking unpredictable runtime behavior and breaking test isolation.

**Comment by lourish** [comment]
Switching `@PostConstruct` to `@Before` still fails in the same way:

```
    @Before
    protected void setUpRandomness() {
        authPrototypes = new AuthPrototypes(RandomizedContext.current());
    }
```

Do you have any examples of filtering to ignore threads out of scope?

**Comment by lourish** [comment]
My apologies, I think I've found the culprit - one of the classes was calling `RandomizedContext.current()` in a constructor which was being called out of the test scope. Thanks for your help in investigating. If you do have any examples of thread scope filtering I could do with a pointer on that! Thanks

**Comment by dweiss** [comment]
See here for an example:
https://github.com/apache/lucene-solr/blob/e2521b2a8baabdaf43b92192588f51e042d21e97/lucene/test-framework/src/java/org/apache/lucene/util/LuceneTestCase.java#L210-L212

In general though, I'd recommend adding some lingering:

@ThreadLeakLingering(linger = 5000) // Wait long for leaked threads to complete before failure.

and if a thread doesn't die before this timeout, it probably means something is not closed or shut down properly.

**Comment by lourish** [comment]
Thanks Dawid, that link was very helpful, I got the thread leak checks working with spring boot
