### ISSUE TITLE
Run tests from a dependency jar

### ISSUE THREAD

**Issue by dadoonet** [randomizedtesting/randomizedtesting#254]
I have a JAR which contains tests.

I'd like to execute the same test suite using different configurations.

Would be great to support that in randomizedtesting project as a configuration option where you can add a jar like:

```xml
<configuration>
   <dependenciesToScan>
     <dependency>groupid:artifactid</dependency>
   </dependenciesToScan>
</configuration>
```

In a similar way as https://issues.apache.org/jira/browse/SUREFIRE-569

Thanks!

**Comment by dweiss** [comment]
The runner is written for ANT, actually. Maven is merely a decoration later. And as such, the Ant runner accepts any kind of test suite definition you can think of (including a reference to a classpath).

Look at "Specifying test suite classes" in http://randomizedtesting.github.io/randomizedtesting/releases/2.5.3/ant/Tasks/junit4.html

**Comment by dadoonet** [comment]
Good to know. Is there a way for the Maven wrapper to specify just artifact coordinates?

**Comment by dweiss** [comment]
additionalClasspathElements?

https://github.com/randomizedtesting/randomizedtesting/blob/master/junit4-maven-plugin/src/main/java/com/carrotsearch/maven/plugins/junit4/JUnit4Mojo.java#L397-L401

**Comment by dweiss** [comment]
Did you check what that path resolves to and if it indeed contains the JAR? 

bq. The later means that I don't have to care about the physical location of the JAR file. It can be in Maven central, in my maven private repo...

Yeah, but it requires the knowledge on how to write it in Maven, which I don't have. Feel free to provide a patch if you'd like to dig in though.
