### ISSUE TITLE
How to expose internal stack trace

### ISSUE THREAD

**Issue by msokolov** [randomizedtesting/randomizedtesting#257]
Hi, this is more of a question than an issue; please LMK if there is a better forum for this...

I am trying to use randomizedtesting in my project. I started from Lucene's common-build.xml and customized for my purposes. When I run the test target in this project, I get an IllegalArgumentException reported on the console with no stack trace, just a line number in my Ant build file corresponding to the junit4 element. I'm trying to understand what I might have done wrong, and after a lot of fiddling with parameters, classpaths, and so on, I don't see anything obviously broken, and I'm wondering -- is there is a way to expose the internal stack trace on the console?

Note: I did comment out the junit4:filtertrace so at least that should not be filtering anything.

I'm happy to follow up with more details if that seems like it would be useful.

OK - I was able to gather a stacktrace by greatly simplifying my setup:

```
/Users/sokolovm/workspace/ProjectX/src/ProjectX/build.xml:56: java.lang.IllegalArgumentException
	at com.carrotsearch.ant.tasks.junit4.dependencies.org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.carrotsearch.ant.tasks.junit4.dependencies.org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.carrotsearch.ant.tasks.junit4.dependencies.org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.carrotsearch.ant.tasks.junit4.JUnit4.processTestResources(JUnit4.java:1713)
	at com.carrotsearch.ant.tasks.junit4.JUnit4.execute(JUnit4.java:879)
...
```

I wonder if there is some sort of JVM incompatibility?? The class files are in a different format than is expected or something?

I do see this in ClassReader:

```
      throw new IllegalArgumentException(
          "Unsupported class file major version " + readShort(classFileOffset + 6));
```

My classes are built with JDK9, so I believe class version = 53.0. As another point of info, I am able to run these test class files using standard ant/junit.

**Comment by dweiss** [comment]
Yes, this looks like class file incompatibility. It's a bit strange because we use Java 9 in our projects too, I'll take a look.

**Comment by msokolov** [comment]
One thing that's odd to me is I believe we are using carrotsearch-randomizedtesting_junit4-ant 2.5.3, yet the line number in that stack trace looks like it must be coming from an older version.

**Comment by dweiss** [comment]
I believe this is in fact the cause -- Lucene (and my projects) compile fine under Java 9, but they emit Java 1.8-compatible bytecode. 

As for the stack trace and the exception -- this should really be reported by ant, I don't see why it's not. If you can share a simple repro I'll be able to tell a bit more.

**Comment by msokolov** [comment]
Hmm thanks for checking. When I set {{<property name="target.java.vm.version" value="8"/>}} I get past that exception. In my simplified setup I do see the full stack trace, but I'll follow up if I can isolate what seems to be swallowing it.

**Comment by dweiss** [comment]
I don't see your build file, but if you're using ant then javac can be configured to consume and emit bytecode using its standard attributes (source, target), see here.

https://ant.apache.org/manual/Tasks/javac.html

**Comment by dweiss** [comment]
Also, the source code contains simple scaffolding for ant and maven, perhaps it'll be useful for you:

https://github.com/randomizedtesting/randomizedtesting/tree/master/examples

**Comment by msokolov** [comment]
Thanks - I do have a successful test run now, after specifying target="8". I'm not sure exactly what part of this fairly complex ant setup is swallowing exception stacks, but I suspect it has nothing to do with carrotsearch, so I'll close this issue now, although I am curious what plans you may have for  JDK 9/10/11 support?

**Comment by dweiss** [comment]
I filed an issue GH-258 to support Java 9 and 10.
