### ISSUE TITLE
Event bus dispatch error: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by szaluk** [randomizedtesting/randomizedtesting#263]
I am seeing the following error when using the 2.6.2 version of the JUnit 4 Ant Task:

`16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] Event bus dispatch error: java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.carrotsearch.randomizedtesting.WriterOutputStream.processInput(WriterOutputStream.java:259)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.carrotsearch.randomizedtesting.WriterOutputStream.write(WriterOutputStream.java:195)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.LocalSlaveStreamHandler$OnDiskStreamEvent.copyTo(LocalSlaveStreamHandler.java:203)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.listeners.TextReport.onOutput(TextReport.java:436)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at java.lang.reflect.Method.invoke(Method.java:498)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.EventBus.post(EventBus.java:212)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.events.aggregated.AggregatingListener.appendToEventStream(AggregatingListener.java:48)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at java.lang.reflect.Method.invoke(Method.java:498)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.dependencies.com.google.common.eventbus.EventBus.post(EventBus.java:212)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.LocalSlaveStreamHandler.pumpEvents(LocalSlaveStreamHandler.java:256)
16:51:12 [Unit, Script Debugger & Electronics] [junit4:junit4] 	at com.carrotsearch.ant.tasks.junit4.LocalSlaveStreamHandler$2.run(LocalSlaveStreamHandler.java:122)`

Any idea what might be causing this?

Thanks,
Steve

**Comment by szaluk** [comment]
@dweiss - Looking online I see the following as the possible cause:

`This problem also happens when you build the software with JDK 9 with target JDK 8, because in JDK9 ByteBuffer.flip() returns a ByteBuffer... It used to return a Buffer in JDK8.

And then you try to run this on JDK8 you get exactly this error.`

Was this artifact built using JDK 9 with JDK 8 as the target?

Thanks,
Steve

**Comment by szaluk** [comment]
Seems like the issue is here:

https://github.com/randomizedtesting/randomizedtesting/blob/1aba3a1fbfe34c10b69ac73452ac8b3d68dc3aa4/randomized-runner/src/main/java/com/carrotsearch/randomizedtesting/WriterOutputStream.java#L259

**Comment by dweiss** [comment]
This is indeed a covariant in JDK9 that results in backward incompatible code, sigh. I'll fix. Thanks for hunting this down.

**Comment by szaluk** [comment]
Thanks!

**Comment by dweiss** [comment]
Can you try 2.6.3 I just pushed to maven central, Steven? Should be on SonaType's release repositories now (central may lag a bit). Thanks.

**Comment by szaluk** [comment]
Sure.  I will update my dependencies and try now.

Thanks,
Steve

**Comment by szaluk** [comment]
@dweiss - New build looks much better.  I will test it out some more tomorrow.

Thanks!
