### ISSUE TITLE
Methods with ( or ) in them can't be selected directly

### ISSUE THREAD

**Issue by nik9000** [randomizedtesting/randomizedtesting#271]
We sometimes use `@ParametersFactory` and end up with method names that contain `(` or `)`. It looks like [`GlobFilter`](https://github.com/randomizedtesting/randomizedtesting/blob/master/randomized-runner/src/main/java/com/carrotsearch/randomizedtesting/GlobFilter.java) doesn't escape `(` or `)`, so when we go to try and select the method we end up not matching the method.

**Comment by dweiss** [comment]
Fixed, hopefully. Thanks Nik.

**Comment by nik9000** [comment]
That looks good. Thanks!

**Comment by dweiss** [comment]
I'll release a bugfix release, but sonatype's nexus hung for me (can't drop the repo); filed an issue there and waiting for resolution.
