### ISSUE TITLE
Find test suites consistently with JUnit

### ISSUE THREAD

**Issue by dsmiley** [randomizedtesting/randomizedtesting#278]
When using RandomizedRunner on an existing project that was previously using JUnit via Maven surefire, RandomizedRunner will complain about tests that don't look right (e.g. no public constructor) when it's not in fact a test suite -- it's some test utility thing.  I know I could rename to not start or end with Test but it'd be nice to not have to.  Addressing this could help adoption.

**Comment by dweiss** [comment]
This is old, but I missed it somehow. You don't have to rename, you need to provide filters to the runner that would exclude such classes.
