### ISSUE TITLE
Executing a Single Test Method using the JUnit 4 Ant Task and Maven Plugin

### ISSUE THREAD

**Issue by szaluk** [randomizedtesting/randomizedtesting#279]
We are using the JUnit4 Ant Task and Maven Plugin to execute all of our tests and we use a large variety of different JUnit 4 runners.  

Is it possible to execute a single test method in a test class?  What would the fileset values for include/exclude look like in the example below?

https://github.com/randomizedtesting/randomizedtesting/blob/master/examples/ant/build.xml#L70

Thanks,
Steve

**Comment by dweiss** [comment]
I somehow missed this, Steve -- sorry. You'd need to use -Dtests.method glob filter. Fileset inclusion/ exclusion takes the entire classes.
