### ISSUE TITLE
why cannot default UnhandledExceptionHandler be changed?

### ISSUE THREAD

**Issue by cscie88-ta** [randomizedtesting/randomizedtesting#285]
I'm upgrading a legacy app written in Groovy that uses both ElasticsearchTestFramework and EmbeddedKafka/Zookeeper frameworks. I'm facing an issue with upgrading from zoookeeper version 3.4 to version 3.5, because in v3.5 Zookeeper added the following static code to do more logging in it's NIOServerCnxnFactory:

```
static {
        Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
                public void uncaughtException(Thread t, Throwable e) {
                    LOG.error("Thread " + t + " died", e);
                }
            });

```
Now, for some reason, ElasticsearchTestFramework requires the use of the RandomizedRunner in order to use it in Unit tests. So, I have to run all unit tests as following:
```
@RunWith(RandomizedRunner.class)
@ThreadLeakScope(ThreadLeakScope.Scope.NONE)
class ElasticsearchClusterSelectorServiceSpec { ... }

```

And, also for some reason the RandomizedRunner does not like when a default UnhandledExceptionHandler is changed! So, when I run the unit tests that run both ES and ZK now I get the following exception: 

**java.lang.RuntimeException: Suite replaced Thread.defaultUncaughtExceptionHandler. It's better not to touch it.  Or at least revert it to what it was before. Current: class org.apache.zookeeper.server.NIOServerCnxnFactory$1**

I'm assuming it is due to this code in the RandomizedRunner:

```
UncaughtExceptionHandler current = Thread.getDefaultUncaughtExceptionHandler();
    if (current != handler) {
      notifier.fireTestFailure(new Failure(suiteDescription, 
          new RuntimeException("Suite replaced Thread.defaultUncaughtExceptionHandler. " +
          		"It's better not to touch it. Or at least revert it to what it was before. Current: " + 
              (current == null ? "(null)" : current.getClass()))));
    }
```

So, two questions:
1. why does RandomizedRunner does not tolerate change in the default exception handler? Or at least does not give me an option to treat it as an issue that warrants failing of the tests vs just ignoring it?
2. is there any other option to work around this issue? (I tried starting ZK in a separate thread but that does not help as the default handler is set for ALL threads ....)

Thank you!
Marina

**Comment by dweiss** [comment]
The default handler is used to cause tests to fail if a forked thread propagated an exception up the stack and didn't handle this anyhow. This is an error, don't you think? What Zookeeper does is wrong (it shouldn't be doing this in static initialization block). You can try to add a class test rule that gets the default handler, "initializes" zookeeper and them restores the handler right after zookeeper has changed it. 

This isn't a bug, it's intentional.

**Comment by cscie88-ta** [comment]
thank you - and sorry I did not notice the answer right away and posted a duplicate question - I thought my issue was not published as I did not see it in the Open list :)

I used your suggestion and added a @ClassRule static method where I first get the default handler, then call the Kafka/ZK setup methods, and then re-set the handler to the original one. It worked.

thank you
