### ISSUE TITLE
why change in the default UncaughtExceptionHandler is not allowed and failes the tests?

### ISSUE THREAD

**Issue by ppine7** [randomizedtesting/randomizedtesting#286]
I'm upgrading a legacy app that uses both Elasticsearch test framework (MockNode and cluster from the org.elasticsearch.test:framework:6.5.3) and EmbeddedKafka/Zookeeper frameworks. I'm facing an issue with upgrading from zoookeeper version 3.4 to version 3.5, because in v3.5 Zookeeper added the following static code to do more logging in it's NIOServerCnxnFactory:
```
static {
        Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
                public void uncaughtException(Thread t, Throwable e) {
                    LOG.error("Thread " + t + " died", e);
                }
            });
```
At the same time it looks like Elasticsearch requires the use of the RandomizedRunner in order to use it in Unit tests. So, I have to run all unit tests as following:

```
@RunWith(RandomizedRunner.class)
@ThreadLeakScope(ThreadLeakScope.Scope.NONE)
class ElasticsearchClusterSelectorServiceSpec { ... }
```
However, the RandomizedRunner does not like when a default UncaughtExceptionHandler is changed! So, when I run the unit tests that run both ES and ZK now I get the following exception:

_**java.lang.RuntimeException: Suite replaced Thread.defaultUncaughtExceptionHandler. It's better not to touch it. Or at least revert it to what it was before. Current: class org.apache.zookeeper.server.NIOServerCnxnFactory$1**_

I'm assuming it is due to this code in the RandomizedRunner:

```
UncaughtExceptionHandler current = Thread.getDefaultUncaughtExceptionHandler();
    if (current != handler) {
      notifier.fireTestFailure(new Failure(suiteDescription, 
          new RuntimeException("Suite replaced Thread.defaultUncaughtExceptionHandler. " +
          		"It's better not to touch it. Or at least revert it to what it was before. Current: " + 
              (current == null ? "(null)" : current.getClass()))));
    }
```

So, my questions:
1. why is changing UncaughtExceptionHandler is causing the tests to fail? Could it at least be made configurable to fail or not to fail?
2. is there any other option to work around this issue? (I tried starting ZK in a separate thread but that does not help as the default handler is set for ALL threads ....)

thank you!
Marina

**Comment by dweiss** [comment]
I replied to this already in gh-285.
