### ISSUE TITLE
IntelliJ displays parameterized tests in an awkward way and won't launch them properly

### ISSUE THREAD

**Issue by dweiss** [randomizedtesting/randomizedtesting#295]

**Comment by donnerpeter** [comment]
Maybe it can be fixed on IntelliJ side, I've filed https://youtrack.jetbrains.com/issue/IDEA-261001

**Comment by dweiss** [comment]
Thanks. It may be the case of different runner implementations providing different test descriptions and IDEs trying to adopt to that.

**Comment by dweiss** [comment]
Seems like the issue has been fixed on intellij side (thank you!).
