### ISSUE TITLE
Thought about BiasedUnicodeGenerator

### ISSUE THREAD

**Issue by mocobeta** [randomizedtesting/randomizedtesting#299]
Hello,

While `UnicodeGenerator` is very useful for detecting bugs that are caused by anomalous inputs, applications often expect restricted or biased inputs (texts). I wonder it might be helpful to have a string generator that generates random but somewhat biased Unicode sequences for some applications' tests (e.g., applications that rely on language-specific logic).
I mean, I look for such a biased random long-sequence generator for our application (not Lucene), and I'm thinking of implementing a `StringGenerator` subclass.

I'm not sure this makes sense to this library; just would like to share my rough thoughts and seek advice if you are interested.

Class-name: `BiasedUnicodeGenerator`
Specs:
- Similar to UnicodeGenerator, it generates random character sequences (by sampling Unicode characters).
- It takes a list of [Unicode range/blocks, weight] pairs via the constructor. The weights must be positive real values, and the sum of them must be equal to or less than 1.0.
- It samples characters from given code ranges according to their weights. 
- If the sum of weights is less than 1.0, (1.0 - sumOfWeights) is equally divided and assigned to the code ranges that are not explicitly given. (I imagine this requirement is not so obvious, though... there could be a more simple approach.)

Thanks.

**Comment by dweiss** [comment]
Hi @mocobeta :) I think it sounds interesting. In my experience the "random" string generator is sufficient to find problems quickly but what you suggest also sounds useful - this one is actually a proof that non-uniform unicode sampling is also useful:

https://github.com/randomizedtesting/randomizedtesting/blob/8be8a09e3b3bf1a57947d5367a1afe68322ac4dc/randomized-runner/src/main/java/com/carrotsearch/randomizedtesting/generators/RealisticUnicodeGenerator.java

maybe it could be made smarter somehow?

A more ambitious project would be to try to train a markov model (or some other model) on various wikipedias and then generate pseudo-content from that! :)

**Comment by mocobeta** [comment]
Thanks, @dweiss, for your reply. I know there is `RealisticUnicodeGenerator`, but I haven't looked at it yet (though I've been wondering what "realistic" means here) - I'll check that.

> A more ambitious project would be to try to train a markov model (or some other model) on various wikipedias and then generate pseudo-content from that! :)

It sounds interesting to me too. After all, I think I look for light-weight language models for testing.

**Comment by mocobeta** [comment]
"Close" command in #300 seems not to work.

**Comment by mocobeta** [comment]
> What I had in mind was slightly different: I wanted a pseudo-language generator that would be pre-trained over a large input of different languages and would generate character sequences that follow that language's character distributions but also respect n-gram character distributions to some extent.

Does it make sense to have a pseudo-text generator that generates completely random or more realistic texts (by giving a seed text or clue words) based on word n-gram models on this repo?  - Say, "FakeTextGenerator" that may consist of an unsupervised LM trainer and inferencer.
Though that's a nice-to-have feature to me, I've been thinking it can be helpful to augment test data (mainly for measuring our algorithms' robustness) without labor, even if it's not a sophisticated text generator.
I just wanted to sketch out my very rough idea; I believe that'd be possible (and hopefully fun), but still have little idea about how to integrate that to the test runner, and then it's not notable enough to create an issue...

**Comment by mocobeta** [comment]
Thanks, I didn't know the tool, but it seems interesting (I wonder if it generates pseudo-words by character n-gram model?).
What I thought is word n-gram based models and they might be bigger than character-based ones; anyway, I'll try to find time to explore this.
