### ISSUE TITLE
Use monotonic times throughout the codebase (not currentTimeMillis)

### ISSUE THREAD

**Issue by dweiss** [randomizedtesting/randomizedtesting#307]
Clock can go back, causing havoc and odd results as shown in 
https://github.com/apache/lucene/issues/7687

**Comment by rmuir** [comment]
Thanks for the work here @dweiss ! Maybe it will a little bite out of the long-tail of jenkins failures :)

**Comment by dweiss** [comment]
Definitely worth trying to cut down on the noise. It's always irritating when a test fails and there's no clue as to what actually happened...
