### ISSUE TITLE
ParametersFactory, use of random to generate the parameters

### ISSUE THREAD

**Issue by dsmiley** [randomizedtesting/randomizedtesting#308]
Imagine you have a  file containing many test inputs.  Instead of testing all of them each time (takes too long), you want to do a random sampling.  Also imagine you'd like to use `ParametersFactory` for various reasons, such as because there is an existing base class to extend that does setup/teardown lifecycle etc. that would be hard to arrange to do otherwise.  I tried this and found that I couldn't use the random context inside the method annotated with `ParametersFactory`.

**Comment by dweiss** [comment]
Selection of test "descriptions" (parameters factory) happens very early in JUnit and that's the reason it's not under any context. But even if this is solvable, I think it'd be confusing to have a different set of test cases from the suite on each run - they'd appear in test outlines, then be gone on each repetition with a different seed. 

A workaround would be to generate all tests cases (from a file or elsewhere) in parameters factory, then decide whether you run the test or skip it at runtime (in a before hook or even in the test) - you can do this at random based on the seed to keep the ratio of tests per run fairly constant (say, 10% of all tests). This also comes with problems though - you'd have all the tests in the tests outline but running a particular test (with different seeds) would either run it or skip it... wouldn't it be confusing for people not familiar with the framework? You can provide a reason for the skipped test, of course, but still...

**Comment by dweiss** [comment]
I've added an example of what I had in mind -- see here:
https://github.com/randomizedtesting/randomizedtesting/blob/master/examples/maven/src/main/java/com/carrotsearch/examples/randomizedrunner/Test019ParameterizedRandomSelection.java

**Comment by dsmiley** [comment]
That's a reasonable approach considering trade-offs; thanks.
