### ISSUE TITLE
Using RandomizedRunner with Groovy Spock tests

### ISSUE THREAD

**Issue by jubui** [randomizedtesting/randomizedtesting#309]
Is it possible to use `@RunWith(RandomizedRunner.class)` with Groovy Spock tests or rather is it possible to do some equivalent thing? It seems we are limited to just JUnit which is a major inconvenience.

**Comment by dweiss** [comment]
The short answer is no. Spock uses its own JUnit runner for the same reasons randomized testing uses one - it provides additional infrastructure around your tests. You can't combine two runners into one.

This said, there's nothing to prevent you from using the same randomization principles in a different test runner - the initial infrastructure can be quite simple - an initial seed selection, followed by random choices from there. In a single-threaded situation this is quite effective (and sufficient) already. This project provides many additional features that are less commonly used in small unit tests (thread leak detection, etc.); perhaps you'll find that they're not useful at all if you're writing Spock tests.
