### ISSUE TITLE
UnicodeGenerator.ofCodePointsLength can generate larger strings than the upper limit

### ISSUE THREAD

**Issue by peternied** [randomizedtesting/randomizedtesting#310]
### Description
When `UnicodeGenerator.ofCodePointsLength(...)` generates the string, in creates a number of characters as defined by the upper limit; however, when translated into a String, depending on the characters, this can create a string that is larger than the upper bounds.

### Expected Results
The returned string's length should always be less than or equal to the codepoint length passed in to the function.

### Additional context
- Reproduced in https://github.com/opensearch-project/OpenSearch/issues/12395
- Local patch https://github.com/opensearch-project/OpenSearch/pull/12415

**Comment by peternied** [comment]
Hmm, on the other hand maybe this isn't correct.  I don't have a clear reproduction with only this library, will need to revisit if we see this issue in other sources

**Comment by dweiss** [comment]
Codepoints do not translate into characters directly - there may be surrogate pairs involved and then the length of the string will be longer.

**Comment by dweiss** [comment]
You may want to take a look at ofCodeUnitsLength - this is more likely what you want if you wish to limit the length of the string. This isn't a bug.

**Comment by peternied** [comment]
Thanks for the comment @dweiss - I agree there is no issue
