### ISSUE TITLE
Race condition calling RandomizedTest.isNightly

### ISSUE THREAD

**Issue by javanna** [randomizedtesting/randomizedtesting#311]
We are hitting a race condition evaluating `RandomizedTest#isNightly`. While the `RandomizedContext` is per thread, the group evaluator is shared and accessed across different ranzomized contexts, hence concurrent calls to [`GroupEvaluator#isGroupEnabled`](https://github.com/randomizedtesting/randomizedtesting/blob/master/randomized-runner/src/main/java/com/carrotsearch/randomizedtesting/GroupEvaluator.java#L166) are not supported. 
We get a `NullPointerException` on the last line despite the test group should be lazily added just before: 

```
return testGroups.get(testGroupAnnotation).enabled;
```

This is unfortunate and comes from multiple threads calling `RandomizedTest#isNightly` concurrently. Simply calling the method before forking to multiple threads should fix it on our end, yet there is probably room for a better fix upstream. If the group evaluator is supposed to be shared across threads, perhaps it should be thread-safe?

**Comment by dweiss** [comment]
Hmm. Looks like a bug indeed. I'll take a look during the weeekend.

**Comment by dweiss** [comment]
I've committed a fix, @javanna . If you care to take a look (or have a way to test it?), it's be great to get a nod of approval. I'll release shortly.

**Comment by dweiss** [comment]
Released 2.8.2.

**Comment by javanna** [comment]
Thanks @dweiss looks good!
